require 'fileutils'

OUT_DIR = ".out"

task :default => :build

task :build do
  FileUtils.mkdir_p('.out')
  File.open(File.join(OUT_DIR, 'rbuild.Rscript'), "w") do |f|
      list = []

      list << "setwd('%s')" % [File.dirname(__FILE__)]
      list << "require('rmarkdown')"
      list << "rmarkdown::render('main.Rmd', 'pdf_document', output_dir='#{OUT_DIR}')"

      f << list.join("\n")
  end

  `Rscript .out/rbuild.Rscript`
end
